### ISSUE TITLE
Events: Event cards are not loading

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/ghost-advisory-theme#225]
See https://beta.advisory.sg, for some reason even though the posts are created correctly, the event cards aren't loaded.

**Comment by partysnax** [comment]
Apparently this is not actually a bug - it's because the dates on the sample event cards used on the beta site are all set before the current day (June 2021), hence them not showing up is the filter working as intended. The dates of the sample events have been modified and they are showing up again.

**Comment by wei2912** [comment]
In that case we should have a placeholder if there are no upcoming events.
